FROM debian:buster

RUN apt update
RUN apt install -y \
	wget \
	lsb-release \
	ca-certificates \
	apt-transport-https \
	software-properties-common \
	gnupg2
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/sury-php.list
RUN wget -qO - https://packages.sury.org/php/apt.gpg | apt-key add -
RUN apt update
RUN apt install php8.1 -y
RUN apt upgrade -y
RUN a2dismod autoindex -f
RUN service apache2 restart
RUN echo "ServerName 127.0.0.1" >> "/etc/apache2/apache2.conf"
RUN apt install php8.1-mysql php8.1-imagick -y
RUN apt install -y sendmail sendmail-cf m4
RUN echo "define('SMART_HOST','smtp.sipartech.com')" >> /etc/mail/sendmail.mc
RUN echo "GENERICS_DOMAIN(localhost.localdomain localhost)dnl" >> /etc/mail/sendmail.mc
RUN echo "MASQUERADE_AS(42nice.fr)dnl" >> /etc/mail/sendmail.mc
RUN m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf

CMD service sendmail start && apachectl -D FOREGROUND
